/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Erpc": {
      "service": string
      "type": "sst.aws.Service"
    }
    "MasterVpc": {
      "type": "sst.aws.Vpc"
    }
    "PonderProdIndexer": {
      "service": string
      "type": "sst.aws.Service"
    }
    "PonderProdReader": {
      "service": string
      "type": "sst.aws.Service"
    }
  }
}
