name: "🚀 Deploy submodule"

on:
  workflow_call:
    inputs:
      runner-label:
        required: false
        type: string
      pr-sha:
        required: true
        type: string
      ref:
        required: true
        type: string
      stage-override:
        required: false
        type: string

jobs:
  deploy-aws:
    runs-on: ${{ inputs.runner-label || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.pr-sha }}
      - uses: oven-sh/setup-bun@v1

      - name: "🔨 Install dependencies"
        run: bun install --frozen-lockfile

      - name: "👥 Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::262732185023:role/github-action-deploy-role
          aws-region: eu-west-1
          retry-max-attempts: 5

      - name: "🚀 SST Deploy"
        env:
          STAGE_OVERRIDE: ${{ inputs.stage-override }}
        run: |
          echo "Deploying with stage: prod"
          bun sst deploy --stage prod
